# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aStartTime', models.DateTimeField(max_length=10)),
                ('aEndTime', models.DateTimeField(max_length=50)),
                ('aDate', models.DateTimeField(max_length=50)),
                ('requestId', models.CharField(max_length=10)),
                ('requestType', models.CharField(max_length=50)),
                ('timeOfSubmittingRequest', models.DateTimeField(max_length=50)),
                ('requestDate', models.DateTimeField(max_length=50)),
                ('requestStartTime', models.DateTimeField(max_length=50)),
                ('requestEndTime', models.DateTimeField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('counselorID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('counselorLName', models.CharField(max_length=50)),
                ('counselorMName', models.CharField(max_length=50)),
                ('counselorFName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Cat', models.CharField(max_length=50)),
                ('Label', models.CharField(max_length=100)),
                ('Value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('studentLName', models.CharField(max_length=50)),
                ('studentMName', models.CharField(max_length=50)),
                ('studentFName', models.CharField(max_length=50)),
                ('studentEmailAddress', models.CharField(max_length=50)),
                ('studentDOB', models.DateField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('trackRepID', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounselorViewPortal.Student'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='counselorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounselorViewPortal.Counselor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CounselorViewPortal.Student'),
        ),
    ]
