# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CounselorViewPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Seq',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='studentAge',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
